# Site settings
title: RayStudio Photography
header-img: img/home-bg.jpg
email: ray@raystudiophoto.com
description: "Write your site description here. It will be used as your sites meta description as well!"
baseurl: "/raystudiophoto"
url: "http://raystudioco.github.io"
twitter_username: raystudio
github_username:  raystudioco
facebook_username:  raystudiophoto

# Build settings
markdown: kramdown
highlighter: pygments
permalink: pretty
paginate: 5
paginate_path: "/page:num/"
paginate_path: "/blog/page:num/"
pages_list:       
  #About: '/about'
  Portfolio: '/portfolio'
  Blog: '/blog'
  Contact: '/contact'
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
