# Site settings
title:RayStudio Photography
header-img: img/home-bg.jpg
email: your-email@yourdomain.com
description: "Write your site description here. It will be used as your sites meta description as well!"
baseurl: ""
url: "http://raystudioco.github.io"
twitter_username: raystudio
github_username:  raystudioco
facebook_username:  raystudiophoto

# Build settings
markdown: kramdown
highlighter: pygments
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
